### ISSUE TITLE
Problem with the Movie Helper

### ISSUE THREAD

**Issue by test01203** [Zaxxon709/909repo#1]
hello 
i change to hebrew for the addon movie helper db 
but as you can see at the picture its only show the title in hebrew and not the poster and the summary of the movie 
can you please fix it ? or please let me know how to do it?

![image](https://github.com/Zaxxon709/909repo/assets/104188844/34f8fc61-1dd1-4e6d-8fc7-346cd71c4115)

**Comment by Zaxxon709** [comment]
![Picture](https://github.com/Zaxxon709/909repo/assets/74501488/f866bac4-8ce4-45c8-87ec-3af1906b1047)

**Comment by test01203** [comment]
> ![Picture](https://user-images.githubusercontent.com/74501488/272867115-f866bac4-8ce4-45c8-87ec-3af1906b1047.jpg)

ok thank you its work . but when i on the kodi front page its still in english 
and i try a lot of skins 
![image](https://github.com/Zaxxon709/909repo/assets/104188844/af8a59b5-adeb-45e6-9bf7-97b9a3d6107a)

**Comment by Zaxxon709** [comment]
Yeah the builds are designed around the English language.

**Comment by The-cpu-max** [comment]
> Yeah the builds are designed around the English language.

Your bulid are excellent and work very well.
But I have to have them be in Hebrew - I managed to change the Hebrew font
But there must be a way to change the language - can you tell me where I can find it?
And the most important thing is that I can't add another category to any skin or edit it

**Comment by test01203** [comment]
> Yeah the builds are designed around the English language.

yes i wants to know also how to do it .. i can to edit file if i had to

**Comment by test01203** [comment]
also look at that in the bulid 
i can see only that 
![image](https://github.com/Zaxxon709/909repo/assets/104188844/3d2f8f7d-8a28-4da9-a2b6-001195037e0e)
and in the addon i get a lot of that 
![image](https://github.com/Zaxxon709/909repo/assets/104188844/0f6e4521-797b-4f78-8d48-b8a751f9b2b2)

**Comment by Zaxxon709** [comment]
@The-cpu-max @test01203 Thanks for your interest in the builds. However, they're designed around the English language. To edit them to work with other languages would require quite a bit of editing. There is more involved then just editing a single file.

**Comment by Zaxxon709** [comment]
> also look at that in the bulid i can see only that ![image](https://user-images.githubusercontent.com/104188844/272889301-3d2f8f7d-8a28-4da9-a2b6-001195037e0e.png) and in the addon i get a lot of that ![image](https://user-images.githubusercontent.com/104188844/272889926-0f6e4521-797b-4f78-8d48-b8a751f9b2b2.png)

This would be an issue with the source of metadata (tmdb)

**Comment by The-cpu-max** [comment]
> @The-cpu-max @test01203 Thanks for your interest in the builds. However, they're designed around the English language. To edit them to work with other languages would require quite a bit of editing. There is more involved then just editing a single file.

I will be very happy to edit and correct what is needed. The loading of your skin is so good. I haven't found any skin that goes up so fast
That's why I will be happy to edit and correct what you want so that everything is presented in my language
If you could just direct me, what needs to be edited and where it would be very helpful to me

**Comment by The-cpu-max** [comment]
> > also look at that in the bulid i can see only that ![image](https://user-images.githubusercontent.com/104188844/272889301-3d2f8f7d-8a28-4da9-a2b6-001195037e0e.png) and in the addon i get a lot of that ![image](https://user-images.githubusercontent.com/104188844/272889926-0f6e4521-797b-4f78-8d48-b8a751f9b2b2.png)
> 
> This would be an issue with the source of metadata (tmdb)

and how we can fix that?

**Comment by Zaxxon709** [comment]
> The

I am quite busy right now and do not have much time for Kodi but I'll have a look into this when I do get time What build is of interest to you?

**Comment by The-cpu-max** [comment]
> > The
> 
> I am quite busy right now and do not have much time for Kodi but I'll have a look into this when I do get time What build is of interest to you?
wow thank you !

fantastic, archic they are the best

**Comment by Zaxxon709** [comment]
> > > The
> > 
> > 
> > I am quite busy right now and do not have much time for Kodi but I'll have a look into this when I do get time What build is of interest to you?
> > wow thank you !
> 
> fantastic, archic they are the best

You're welcome!

**Comment by Zaxxon709** [comment]
@test01203 To edit the build  for the Hebrew language would require quite a bit of editing. There is more involved then just editing a single file.

I will look into editing the build when I have time. No promises

**Comment by test01203** [comment]
> @test01203 To edit the build for the Hebrew language would require quite a bit of editing. There is more involved then just editing a single file.
> 
> I will look into editing the build when I have time. No promises

It is understandable that it is not simple.  In any case, I would like to know the names of the files that need to be edited?  And secondly, is it necessary to edit the skin or the addon?

**Comment by Zaxxon709** [comment]
> > @test01203 To edit the build for the Hebrew language would require quite a bit of editing. There is more involved then just editing a single file.
> > I will look into editing the build when I have time. No promises
> 
> It is understandable that it is not simple. In any case, I would like to know the names of the files that need to be edited? And secondly, is it necessary to edit the skin or the addon?

I am unsure of all the files that would need to be edited. That's why I said I would look into it when I have time.

**Comment by test01203** [comment]
> @The-cpu-max @test01203 I had a quick look at this and due to the amount of files that need to be edited I have decided to not take on the task of converting these builds to Hebrew. I just do not have the free time. It would be more practical to start fresh.
> 
> My advice, choose your skin of choice and edit it to function with the Hebrew language. Then create your own, Hebrew only build.

That's exactly the point I can't figure out how your bulid works I tried to do something similar but ,its slow. In your bulid the movies and series were preloaded Which is also why it will go up quickly .And when I for example put the category of popular from the movie db it loads slowly So what should be done? How can I preload?

**Comment by Zaxxon709** [comment]
@test01203 I have to admit, there is a lot going on behind the scenes in my builds. If you're interested in learning I will create a telegram group and you can join. I'll then help you create your Hebrew build. You do the work, I'll answer questions and guide you along.

**Comment by Zaxxon709** [comment]
@test01203 I have to admit, there is a lot going on behind the scenes in my builds. If you're interested in learning I will create a telegram group and you can join. I'll then help you create your Hebrew build. You do the work, I'll answer questions and guide you along.

**Comment by Zaxxon709** [comment]
Below is a Telegram group invite. Join and I will assist with converting to Hebrew there. Cheers

https://t.me/+NWH55TOTTBczMDdh

**Comment by test01203** [comment]
> Below is a Telegram group invite. Join and I will assist with converting to Hebrew there. Cheers
> 
> https://t.me/+NWH55TOTTBczMDdh

ok i am in 
![image](https://github.com/Zaxxon709/909repo/assets/104188844/e49a8c08-4371-4d16-bbd8-aadc8f051c5c)

**Comment by Zaxxon709** [comment]
> > Below is a Telegram group invite. Join and I will assist with converting to Hebrew there. Cheers
> > https://t.me/+NWH55TOTTBczMDdh
> 
> ok i am in ![image](https://user-images.githubusercontent.com/104188844/273611877-e49a8c08-4371-4d16-bbd8-aadc8f051c5c.png)

OK great

**Comment by test01203** [comment]
> > > Below is a Telegram group invite. Join and I will assist with converting to Hebrew there. Cheers
> > > https://t.me/+NWH55TOTTBczMDdh
> > 
> > 
> > ok i am in ![image](https://user-images.githubusercontent.com/104188844/273611877-e49a8c08-4371-4d16-bbd8-aadc8f051c5c.png)
> 
> OK great

I have no way to respond to you
You opened a Telegram channel and not a group

**Comment by Zaxxon709** [comment]
@test01203 https://t.me/+EWvv61KyCp04MjAx

**Comment by The-cpu-max** [comment]
> @The-cpu-max I decided to convert EstuaryFlix to Hebrew. You can find it in my wizard. Cheers

wow!! I checked and it looks really good
I would be happy, if it's not complicated, for you to do it for the arctic horizon skin as well
Or if you can get a new skin for him skin arctic fuse
https://github.com/jurialmunkey/skin.arctic.fuse
